from typing import Protocol

class AppLogger(Protocol):
    def debug(self, msg: str) -> None: ...
    def info(self, msg: str) -> None: ...
    def error(self, msg: str) -> None: ...
    def warn(self, msg: str) -> None: ...
